package com.varun.esa;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class errorFrame {
    private JPanel errorPanel;
    private JLabel lblError;
    private JLabel lblBeingAPrick;
    private JButton btnStartAgain;
    JFrame frame = new JFrame("errorFrame");


    public errorFrame() {
        //JFrame frame = new JFrame("errorFrame");
        frame.setContentPane(errorPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
        frame.setBackground(Color.BLUE);
        btnStartAgain.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                frame.dispose();
                new Welcome();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        errorPanel = new JPanel();
        errorPanel.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        errorPanel.setBackground(new Color(-16250559));
        errorPanel.setForeground(new Color(-986896));
        errorPanel.setPreferredSize(new Dimension(600, 400));
        lblError = new JLabel();
        lblError.setBackground(new Color(-16250559));
        lblError.setForeground(new Color(-986896));
        lblError.setText("THIS ARTSIT DOESN'T EXIST IN OUR DATBASE . . .");
        errorPanel.add(lblError, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblBeingAPrick = new JLabel();
        lblBeingAPrick.setBackground(new Color(-16250559));
        lblBeingAPrick.setForeground(new Color(-986896));
        lblBeingAPrick.setText("WHO DO YOU LISTEN TO?");
        errorPanel.add(lblBeingAPrick, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnStartAgain = new JButton();
        btnStartAgain.setBackground(new Color(-16715776));
        btnStartAgain.setForeground(new Color(-986896));
        btnStartAgain.setText("START AGAIN");
        errorPanel.add(btnStartAgain, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return errorPanel;
    }

}
