package com.varun.esa;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.neelkamath.euphonia.Quizmaster;
import com.neelkamath.euphonia.api.ArtistMetadata;
import com.varun.esa.utils.CommonUtils;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.Iterator;
import java.util.List;

public class yearQ {
    private JButton Next;
    private JPanel yearPanel;
    private JLabel lblYearQ;
    private JRadioButton radioButton1;
    private JRadioButton radioButton2;
    private JRadioButton radioButton3;
    private JRadioButton radioButton4;
    private JFrame frame = new JFrame("yearQ");

    ButtonGroup yearGroup = new ButtonGroup();

    public void checkYearAnswer(Quizmaster Q, ButtonGroup yearGroup, Score score) {
        String answer = Q.getQuiz().getReleasedQuestion().getAnswer();
        String selectedYear = CommonUtils.getSelectedButtonText(yearGroup);
        if (selectedYear != null && selectedYear.equalsIgnoreCase(answer)) {
            score.increment();
        }
    }

    public yearQ(List<ArtistMetadata> artists, Score score, int Selection) throws IOException {
        frame.setContentPane(yearPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
        //frame.setBackground(Color.BLUE);

        Quizmaster Q = new Quizmaster(artists.get(Selection));
        lblYearQ.setText(Q.getQuiz().getReleasedQuestion().getQuestion());
        Iterator<String> i = Q.getQuiz().getReleasedQuestion().getOptions().iterator();

        yearGroup.add(radioButton1);
        yearGroup.add(radioButton2);
        yearGroup.add(radioButton3);
        yearGroup.add(radioButton4);

        Iterator<AbstractButton> yearButtonIterator = yearGroup.getElements().asIterator();
        while (yearButtonIterator.hasNext()) {
            JRadioButton Button = (JRadioButton) yearButtonIterator.next();
            if (i.hasNext()) {
                String text = i.next();
                if (text == null || text.length() == 0) {
                    Button.setText("Sorry, No option");
                } else {
                    Button.setText(text);
                }
            } else {
                Button.setText("Sorry, No option");
            }
        }

        Next.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                checkYearAnswer(Q, yearGroup, score);
                if (CommonUtils.getSelectedButtonText(yearGroup) == null) {
                    lblYearQ.setText("Please select an Option");
                } else {
                    try {
                        frame.dispose();
                        new countryQ(artists, score, Selection);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        yearPanel = new JPanel();
        yearPanel.setLayout(new GridLayoutManager(6, 1, new Insets(0, 0, 0, 0), -1, -1));
        yearPanel.setBackground(new Color(-16250559));
        yearPanel.setForeground(new Color(-986896));
        yearPanel.setPreferredSize(new Dimension(600, 400));
        Next = new JButton();
        Next.setBackground(new Color(-16715776));
        Next.setForeground(new Color(-986896));
        Next.setText("NEXT");
        yearPanel.add(Next, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblYearQ = new JLabel();
        lblYearQ.setBackground(new Color(-16250559));
        lblYearQ.setForeground(new Color(-986896));
        lblYearQ.setText("Label");
        yearPanel.add(lblYearQ, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        radioButton1 = new JRadioButton();
        radioButton1.setBackground(new Color(-16250559));
        radioButton1.setForeground(new Color(-986896));
        radioButton1.setText("RadioButton");
        yearPanel.add(radioButton1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        radioButton2 = new JRadioButton();
        radioButton2.setBackground(new Color(-16250559));
        radioButton2.setForeground(new Color(-986896));
        radioButton2.setText("RadioButton");
        yearPanel.add(radioButton2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        radioButton3 = new JRadioButton();
        radioButton3.setBackground(new Color(-16250559));
        radioButton3.setForeground(new Color(-986896));
        radioButton3.setText("RadioButton");
        yearPanel.add(radioButton3, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        radioButton4 = new JRadioButton();
        radioButton4.setBackground(new Color(-16250559));
        radioButton4.setForeground(new Color(-986896));
        radioButton4.setText("RadioButton");
        yearPanel.add(radioButton4, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return yearPanel;
    }

}
